# Generated by Django 5.2.8 on 2025-11-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepicker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarslot',
            options={'ordering': ['day_order', 'time']},
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='day_order',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
